services:
  postgres:
    image: postgres:10.3
    restart: always
    environment:
      - POSTGRES_USER=order-wani
      - POSTGRES_PASSWORD=24W95903e
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
volumes:
  postgres: